### ISSUE TITLE
Normalize naming and formatting conventions across the project

### ISSUE THREAD

**Issue by AlexArchive** [AlexArchive/Validator#36]
What is says on the tin.

**Comment by mgmccarthy** [comment]
AlexArchive, what specific naming and formatting conventions were you thinking of normalizing across the project?

**Comment by ledbutter** [comment]
@mgmccarthy While I don't know what--specifically--Alex meant, I'd say a good starting point would be to simply follow MSDN [guidelines](https://msdn.microsoft.com/en-us/library/ms229002(v=vs.110).aspx)

**Comment by mgmccarthy** [comment]
ledbutter, I forked Validator, Cloned it, did some work, syned with fork. Do you want a pull request next so you can check out some the changes? It's mainly C# 6 changes and some code clean-up/reformatting. I ran all tests before syncing. There is really no functionality changes.

**Comment by mgmccarthy** [comment]
ledbutter, since you've taken ownership of this repository, are you still enforcing these guidelines for contributing?
https://github.com/AlexArchive/Validator/blob/master/Contributing.Md

If so, I'll have to review my changes before I create a pull request to make sure one of the stylistic changes and/or C# changes violate these guidelines

**Comment by ledbutter** [comment]
@mgmccarthy I'd say that yes, the guidelines generally still hold, but if you have a compelling reason to not follow one or more of them, we can discuss in a PR.

If you do have changes to address this issue ready to go, feel free to PR it and reference this issue.

Thanks!

**Comment by ledbutter** [comment]
Addressed in PR #43
